[project]
name = "bbmanager"
version = "0.1.0"
description = "Default template for PDM package"
authors = [
    {name = "Edgar", email = "nekrum@gmail.com"},
]
dependencies = ["click>=8.1.8", "loguru>=0.7.3", "httpx>=0.28.1", "python-dotenv>=1.0.1"]
requires-python = "==3.12.*"
readme = "README.md"
license = {text = "MIT"}


[tool.pdm]
distribution = true

[dependency-groups]
dev = [
    "pytest>=8.3.4",
]

[project.scripts]
list-projects = "bbmanager.cli_functions:list_projects"
create-project = "bbmanager.cli_functions:create_project"
list-repositories = "bbmanager.cli_functions:list_repositories"
create-repository = "bbmanager.cli_functions:create_repository"
